name: dst Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - dst/**

permissions:
  id-token: write
  contents: read

jobs:
  push_to_registry:
    name: Push dst image to ECR Public
    runs-on: game-containers-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::848765924217:role/ci-game-containers-hub
          aws-region: us-east-1

      - name: Login to ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dst
          file: ./dst/Dockerfile
          push: true
          tags: |
            public.ecr.aws/k8k6f0h1/dst:latest
            public.ecr.aws/k8k6f0h1/dst:${{ steps.date.outputs.date }}
